<?xml version="1.0" encoding="utf-8"?><Database Name="TaskManagementProject" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TaskManagementProject.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TaskManagementProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AltechEmployee" Member="AltechEmployees">
    <Type Name="AltechEmployee">
      <Column Name="Emp_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Division" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Skills" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Division" Member="Divisions">
    <Type Name="Division">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Division_Team" Member="Teams" ThisKey="Id" OtherKey="DivisionID" Type="Team" />
      <Association Name="Division_Incident" Member="Incidents" ThisKey="Id" OtherKey="DivisionID" Type="Incident" />
    </Type>
  </Table>
  <Table Name="dbo.Notification" Member="Notifications">
    <Type Name="Notification">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="From_Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="To_Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Veiwed" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Skills" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isAssigner" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="isTeamLeader" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TeamLeading" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DivisionUnder" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TeamUnder" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TeamLeader" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Division_Team" Member="Division" ThisKey="DivisionID" OtherKey="Id" Type="Division" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceLevelAgreements" Member="ServiceLevelAgreements">
    <Type Name="ServiceLevelAgreement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Urgent" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="High" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Normal" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Low" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Division" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Incidedent" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback" Member="Feedbacks">
    <Type Name="Feedback">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ticketID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Priority_Level" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Assigned_To" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Assigned_By" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Deadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Completed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Division_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Team_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Incident_Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Incident" Member="Incidents">
    <Type Name="Incident">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamID" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Division_Incident" Member="Division" ThisKey="DivisionID" OtherKey="Id" Type="Division" IsForeignKey="true" />
    </Type>
  </Table>
</Database>